# Environment vars for testing
export PORT=8000
export STARTUP_FILE=/tmp/startup2
export LIVENESS_FILE=/tmp/liveness2
export READINESS_FILE=/tmp/readiness2
export LISTEN_DELAY_SECONDS=3
export LIVENESS_DELAY_SECONDS=1
export READINESS_DELAY_SECONDS=3
export RESPONSE_DELAY_MILLISECONDS=500
export LIVENESS_SUCCESS_MAX=3
export READINESS_SUCCESS_MAX=3
